// Medication Options for Prescriptions
// Predefined options for dosage, frequency, duration, and instructions

export const DOSAGE_OPTIONS = [
  '100mg',
  '200mg', 
  '250mg',
  '300mg',
  '400mg',
  '500mg',
  '600mg',
  '750mg',
  '1000mg',
  '1 Tablet',
  '2 Tablets',
  '3 Tablets',
  '1 Capsule',
  '2 Capsules',
  '1 Teaspoon',
  '2 Teaspoons',
  '1 Tablespoon',
  '2 Tablespoons',
  '5ml',
  '10ml',
  '15ml',
  '20ml',
  '1 Drop',
  '2 Drops',
  '3 Drops',
  '5 Drops',
  '1 Patch',
  '1 Injection',
  '1 Suppository',
  '2 Suppositories'
]

export const FREQUENCY_OPTIONS = [
  '1x per day',
  '2x per day',
  '3x per day',
  '4x per day',
  'Every 4 hours',
  'Every 6 hours',
  'Every 8 hours',
  'Every 12 hours',
  'Every 24 hours',
  'As needed',
  'Before meals',
  'After meals',
  'With meals',
  'Before bedtime',
  'In the morning',
  'At noon',
  'In the evening',
  'Weekly',
  'Bi-weekly',
  'Monthly',
  'Every other day',
  'Every 3 days',
  'Every 4 days',
  'Every 5 days',
  'Every 6 days',
  'Every 7 days',
  'Every 2 weeks',
  'Every 3 weeks',
  'Every 4 weeks',
  'Every 6 weeks',
  'Every 8 weeks',
  'Every 12 weeks'
]

export const DURATION_OPTIONS = [
  'Daily',
  'Weekly',
  'Monthly',
  '1 day',
  '2 days',
  '3 days',
  '4 days',
  '5 days',
  '6 days',
  '7 days',
  '10 days',
  '14 days',
  '21 days',
  '28 days',
  '30 days',
  '1 week',
  '2 weeks',
  '3 weeks',
  '4 weeks',
  '6 weeks',
  '8 weeks',
  '12 weeks',
  '16 weeks',
  '20 weeks',
  '24 weeks',
  '1 month',
  '2 months',
  '3 months',
  '4 months',
  '5 months',
  '6 months',
  '8 months',
  '10 months',
  '12 months',
  '18 months',
  '24 months',
  'Until symptoms improve',
  'Until further notice',
  'As directed by doctor',
  'Continuous',
  'Short-term',
  'Long-term',
  'Indefinite'
]

export const INSTRUCTIONS_OPTIONS = [
  'Before Food',
  'After Food',
  'Morning',
  'Night',
  'Lunchtime',
  'Take with food',
  'Take on empty stomach',
  'Take before meals',
  'Take after meals',
  'Take with plenty of water',
  'Take with milk',
  'Take with juice',
  'Take at bedtime',
  'Take in the morning',
  'Take in the evening',
  'Take at the same time each day',
  'Do not crush or chew',
  'Swallow whole',
  'Chew thoroughly',
  'Dissolve in mouth',
  'Apply to clean, dry skin',
  'Apply to affected area only',
  'Avoid contact with eyes',
  'Store in refrigerator',
  'Store at room temperature',
  'Keep away from heat',
  'Keep away from light',
  'Shake well before use',
  'Do not shake',
  'Use within 30 days of opening',
  'Discard after expiration date',
  'Do not drive or operate machinery',
  'Avoid alcohol',
  'Avoid sun exposure',
  'Use sunscreen',
  'Monitor blood pressure',
  'Monitor blood sugar',
  'Check weight regularly',
  'Report side effects immediately',
  'Complete full course',
  'Do not stop abruptly',
  'Gradually reduce dose',
  'Take as needed for pain',
  'Take only when symptoms occur',
  'Use sparingly',
  'Apply thin layer',
  'Massage gently',
  'Leave on for specified time',
  'Rinse thoroughly',
  'Do not rinse',
  'Use with caution in elderly',
  'Not recommended during pregnancy',
  'Consult doctor if pregnant',
  'Consult doctor if breastfeeding',
  'May cause drowsiness',
  'May cause dizziness',
  'May cause nausea',
  'May cause dry mouth',
  'May cause constipation',
  'May cause diarrhea',
  'May cause headache',
  'May cause rash',
  'May cause allergic reaction',
  'Stop if allergic reaction occurs',
  'Seek medical attention if severe',
  'Call doctor if symptoms worsen',
  'Follow up in specified time',
  'Return for follow-up appointment'
]

// Helper function to get filtered options based on search term
export const getFilteredOptions = (options: string[], searchTerm: string): string[] => {
  if (!searchTerm) return options
  return options.filter(option => 
    option.toLowerCase().includes(searchTerm.toLowerCase())
  )
}

// Helper function to add custom option
export const addCustomOption = (options: string[], newOption: string): string[] => {
  if (!newOption || options.includes(newOption)) return options
  return [newOption, ...options]
}
